apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nodeport
  labels:
    kubernetes.io/service-name: nodeport
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - "10.244.0.4"